### PR TITLE
Update documents to reflect the latest state-of-the-art 

### PR DESCRIPTION
**Pull request by andremolnar**
Update documents to reflect the latest state-of-the-art as it relates to linting.
Remove old plugins for scss-lint so this repo walks the new talk.

### CODE REVIEW

**Review by AWaselnuk — COMMENTED** [review]
Is it possible that there are any consumers who are relying on those plugins you deleted?

**Comment by andremolnar** [comment]
@AWaselnuk Good question.  One which I cannot yet answer.  The alternative would be to mark them as deprecated - with a time to End of Life.

I can gain more context.  In the mean time the files can be left in and I'll add a note.

FWIW I'm not sure if I would be directly consuming items from a documentation repo, but that doesn't mean others wouldn't be.

**Comment by AWaselnuk** [comment]
@andremolnar yeah I'm not sure about it either. I honestly don't know how people would have consumed those. Might be worth asking around a little bit though.

If you ask in a few Slack channels that might be enough to keep this as is. Not sure if we need to bother with a longer deprecation process.

**Comment by dfmcphee** [comment]
> Is it possible that there are any consumers who are relying on those plugins you deleted?

I don't think so. These were only here as a reference and consumers were copying to their own projects to use (same with the scss-lint config). Should be fine to delete. 👍

**Review by AWaselnuk — APPROVED** [review]
We can 🚢  this as @dfmcphee's comment clarifies things regarding consumer support.

**Pull request merged**
